import type { FileRecord } from "../types";

const FILENAME_QUERIES: Record<string, string> = {
  "package.json": "npm (software)",
  "package-lock.json": "npm (software)",
  "yarn.lock": "Yarn (package manager)",
  "pnpm-lock.yaml": "pnpm",
  "bun.lockb": "Bun (software)",
  "cargo.toml": "Cargo (software)",
  "cargo.lock": "Cargo (software)",
  "go.mod": "Go (programming language)",
  "go.sum": "Go (programming language)",
  "pyproject.toml": "Python (programming language)",
  "requirements.txt": "Pip (package manager)",
  "pipfile": "Pipenv",
  "gemfile": "RubyGems",
  "rakefile": "Rake (software)",
  "makefile": "Make (software)",
  "cmakelists.txt": "CMake",
  "dockerfile": "Docker (software)",
  "docker-compose.yml": "Docker Compose",
  "docker-compose.yaml": "Docker Compose",
  "compose.yml": "Docker Compose",
  ".gitignore": "Git",
  ".gitattributes": "Git",
  ".dockerignore": "Docker (software)",
  ".editorconfig": "EditorConfig",
  ".eslintrc": "ESLint",
  ".eslintrc.js": "ESLint",
  ".eslintrc.json": "ESLint",
  ".prettierrc": "Prettier",
  "tsconfig.json": "TypeScript",
  "vite.config.ts": "Vite (software)",
  "vite.config.js": "Vite (software)",
  "webpack.config.js": "Webpack",
  "rollup.config.js": "Rollup (JavaScript)",
  "tailwind.config.js": "Tailwind CSS",
  "tailwind.config.ts": "Tailwind CSS",
  "readme.md": "README",
  "readme": "README",
  "license": "Software license",
  "license.md": "Software license",
  "changelog.md": "Changelog",
  "tauri.conf.json": "Tauri (software)",
};

const EXTENSION_QUERIES: Record<string, string> = {
  ts: "TypeScript",
  tsx: "TypeScript",
  js: "JavaScript",
  jsx: "JavaScript",
  mjs: "JavaScript",
  cjs: "JavaScript",
  py: "Python (programming language)",
  rs: "Rust (programming language)",
  go: "Go (programming language)",
  java: "Java (programming language)",
  kt: "Kotlin (programming language)",
  scala: "Scala (programming language)",
  c: "C (programming language)",
  cpp: "C++",
  cc: "C++",
  h: "C (programming language)",
  hpp: "C++",
  cs: "C Sharp (programming language)",
  rb: "Ruby (programming language)",
  php: "PHP",
  swift: "Swift (programming language)",
  sh: "Bash (Unix shell)",
  bash: "Bash (Unix shell)",
  zsh: "Z shell",
  fish: "Fish (Unix shell)",
  json: "JSON",
  yaml: "YAML",
  yml: "YAML",
  toml: "TOML",
  xml: "XML",
  md: "Markdown",
  mdx: "MDX (Markdown)",
  rst: "ReStructuredText",
  tex: "LaTeX",
  css: "CSS",
  scss: "Sass (stylesheet language)",
  sass: "Sass (stylesheet language)",
  less: "Less (stylesheet language)",
  html: "HTML",
  svg: "SVG",
  vue: "Vue.js",
  svelte: "Svelte",
  astro: "Astro (web framework)",
  sql: "SQL",
  graphql: "GraphQL",
  gql: "GraphQL",
  lua: "Lua (programming language)",
  dart: "Dart (programming language)",
  ex: "Elixir (programming language)",
  exs: "Elixir (programming language)",
  erl: "Erlang (programming language)",
  hs: "Haskell",
  clj: "Clojure",
  fs: "F Sharp (programming language)",
  ml: "OCaml",
  nim: "Nim (programming language)",
  zig: "Zig (programming language)",
  ps1: "PowerShell",
  png: "Portable Network Graphics",
  jpg: "JPEG",
  jpeg: "JPEG",
  gif: "GIF",
  webp: "WebP",
  avif: "AVIF",
  bmp: "BMP file format",
  pdf: "PDF",
  zip: "ZIP (file format)",
  tar: "Tar (computing)",
  gz: "Gzip",
  mp3: "MP3",
  mp4: "MPEG-4",
  wav: "WAV",
  flac: "FLAC",
};

const GENERIC_FOLDER_NAMES = new Set([
  "src",
  "lib",
  "dist",
  "build",
  "out",
  "bin",
  "obj",
  "target",
  "node_modules",
  "vendor",
  "tests",
  "test",
  "docs",
  "doc",
  "assets",
  "public",
  "static",
  "tmp",
  "temp",
  "cache",
  ".git",
  "__pycache__",
]);

/** Derive a Wikipedia-friendly query term for a file or folder. */
export function wikiQueryFor(record: FileRecord): string | null {
  const lower = record.name.toLowerCase();

  if (FILENAME_QUERIES[lower]) return FILENAME_QUERIES[lower];

  if (record.isDir) {
    if (GENERIC_FOLDER_NAMES.has(lower)) return null;
    return record.name;
  }

  if (record.extension) {
    const hit = EXTENSION_QUERIES[record.extension.toLowerCase()];
    if (hit) return hit;
  }

  return null;
}
